In [1]:
import numpy as np

In [3]:
x= np.random.random(10000000)

In [4]:
x

array([0.19617457, 0.87230544, 0.2053897 , ..., 0.04853297, 0.71364156,
       0.2748621 ])

# time difference between numpy and python

In [5]:
import time 

In [7]:
# python 
start = time.time()
sum(x)/len(x)
print(time.time() - start)

1.640625238418579


In [8]:
# numpy
start = time.time()
np.mean(x)
print(time.time()- start)

0.011059761047363281


In [9]:
import numpy as np
x= np.array([1,2,3,4,5])

In [10]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
x.dtype

dtype('int64')

In [12]:
x.shape 

(5,)

In [16]:
y = np.array([[1,2,3,],[4,5,6],[7,8,9],[10,11,12]])

In [17]:
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
 y.shape

(4, 3)

In [19]:
x = np.array(['Hello', "World"])
print(x)

['Hello' 'World']


In [20]:
print("shape", x.shape)
print("type", type(x))
print('dtype',x.dtype)

shape (2,)
type <class 'numpy.ndarray'>
dtype <U5


In [22]:
x =np.array([1,2.5,4])
print(x,x.dtype)

[1.  2.5 4. ] float64


In [24]:
x = np.array([1.5, 2.2,3.7], dtype = np.int64)
print(x)
print("dtype:", x.dtype)

[1 2 3]
dtype: int64


In [25]:
x = np.array([1,2,3,4,5])
np.save("my_array",x)

In [26]:
my_list = [1,2,3,4,5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [27]:
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
print('dtype:', x.dtype) 

dtype: float64


In [29]:
x = np.zeros((3,4), dtype = int )
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [31]:
x = np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
x = np.full((4,3),5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [34]:
print(x.dtype)

int64


In [36]:
# identity matrix
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [39]:
# diagonal matrix
x = np.diag([10,20,30,40])
print(x)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [43]:
x= np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
x = np.arange(4,10)
print(x)

[4 5 6 7 8 9]


In [46]:
x = np.arange(1,14,3)
print(x)

[ 1  4  7 10 13]


In [49]:
 # for floating point intervals we use np.linspace
x = np.linspace(0,25,10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [51]:
x = np.linspace(0,25,10, endpoint =False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [52]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [53]:
x = np.reshape(x,(4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [57]:
y = np.arange(20).reshape((10,2))
print(y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [59]:
x = np.linspace(0,50,10, endpoint = False).reshape(5,2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [60]:
x = np.random.random((3,3)) 
print(x)

[[0.58602907 0.38022104 0.58273011]
 [0.17612361 0.89827789 0.44784992]
 [0.52858741 0.34795339 0.83709913]]


In [62]:
x = np.random.randint(4,15,(3,2))
print(x)

[[ 8 11]
 [ 8  9]
 [ 7 10]]


In [64]:
x = np.random.normal(0,0.1, size =(1000,1000))
print(x)

[[-0.09474685 -0.05057977  0.12856704 ... -0.07487862 -0.04702834
   0.17945647]
 [-0.14682464  0.05254708 -0.06739038 ...  0.02217409  0.07495756
   0.06307703]
 [ 0.16038004 -0.07330863 -0.11058567 ...  0.10189712  0.11143339
  -0.06118792]
 ...
 [ 0.06349638 -0.05586795 -0.15157222 ... -0.07657432 -0.18714368
   0.04758508]
 [ 0.02624069  0.0804797   0.0125852  ...  0.0198527  -0.02477872
   0.04521945]
 [-0.05128622 -0.22892415 -0.07584333 ...  0.03213429 -0.02679889
   0.03929155]]


In [66]:
print("mean:", x.mean())
print('std',x.std())
print('max:',x.max())
print('min:',x.min())
print("# positive:", (x>0).sum())
print("# negetive:", (x<0).sum())

mean: -1.7373431767738087e-05
std 0.09990990531993894
max: 0.5621763365431937
min: -0.5199228316785552
# positive: 500003
# negetive: 499997


In [67]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [68]:
print(x+y)

[ 6  8 10 12]


In [69]:
print(np.add(x,y))

[ 6  8 10 12]


In [70]:
print(x- y)
print(np.subtract(x,y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]


In [71]:
print(x*y)
print(np.multiply(x,y))

[ 5 12 21 32]
[ 5 12 21 32]


In [72]:
print(x/y)
print(np.divide(x,y))

[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [75]:
 print(np.sqrt(x))


[1.         1.41421356 1.73205081 2.        ]


In [74]:
print(np.power(x,2))

[ 1  4  9 16]


In [76]:
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [78]:
 x = np.arange(25).reshape(5,5)

In [79]:
print(x[x>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [81]:
print(x[x<= 7])

[0 1 2 3 4 5 6 7]


In [82]:
print(x[(x>10)& (x<17)])

[11 12 13 14 15 16]


In [84]:
# numpy also supports set operations 
x= np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

In [85]:
print(np.intersect1d(x,y))

[2 4]


In [86]:
print(np.setdiff1d(x,y))

[1 3 5]


In [89]:
print(np.union1d(x,y))

[1 2 3 4 5 6 7 8]


In [90]:
x = np.random.randint(1,11,size=(10,))
print(x)

[8 4 5 3 5 3 9 9 3 3]


In [91]:
print(np.sort(x))
print(x)

[3 3 3 3 4 5 5 8 9 9]
[8 4 5 3 5 3 9 9 3 3]


In [94]:
x.sort()
print(x)

[3 3 3 3 4 5 5 8 9 9]


In [1]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [2]:
print('1st element :', x[0])
print('2nd element :', x[1])
print('5th element :', x[4])

1st element : 1
2nd element : 2
5th element : 5


In [3]:
print('1st element :', x[-5])
print('2nd element :', x[-4])
print('5th element :', x[-1])

1st element : 1
2nd element : 2
5th element : 5


In [4]:
x[3] =20
print(x)

[ 1  2  3 20  5]


In [5]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print("element at (0,0):", x[0,0])
print("element at (0,1):", x[0,1])
print("element at (2,2):", x[2,2])

element at (0,0): 1
element at (0,1): 2
element at (2,2): 9


In [7]:
x[0,0] = 20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


 # deleting 
    

In [9]:
# one dimentional
x = np.array([1,2,3,4,5])
print(x)

x = np.delete(x,[0,4])
print(x)

[1 2 3 4 5]
[2 3 4]


In [14]:
# two dimentional
y = np.arange(1,10).reshape(3,3)
print(y)

w = np.delete(y, 0, axis =0)
print("\n", w)

v = np.delete(y, [0,2] ,axis =1)
print("\n", v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [20]:
# append 
x = np.array([1,2,3,4,5])
print(x)


x = np.append(x,6)
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [21]:
x = np.append(x, [7,8])
print(x)


[1 2 3 4 5 6 7 8]


In [22]:
y = np.arange(1,10).reshape(3,3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
w = np.append(y,[[10,11,12]] , axis =0)
print(w)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
v = np.append(y , [[10], [11], [12]], axis =1)
print(v)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [25]:
x = np.array([1,2,5,6,7])
print(x)

[1 2 5 6 7]


In [26]:
x = np.insert(x,2, [3,4])
print(x)

[1 2 3 4 5 6 7]


In [28]:
y = np.array([[1,2,3] , [7,8,9]])
print(y)

[[1 2 3]
 [7 8 9]]


In [31]:
v = np.insert (y ,1,5, axis=1)
print(v)

[[1 5 2 3]
 [7 5 8 9]]


#  stacking numpy arrays 


In [32]:
x = np.array([1,2])
print(x)

[1 2]


In [34]:
y = np.array([[3,4],[5,6]])
print(y)

[[3 4]
 [5 6]]


In [35]:
z = np.vstack((x,y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [38]:
w = np.hstack((y, x.reshape(2,1)))
print(w)

[[3 4 1]
 [5 6 2]]


 # slicing in numpy array
 
 - ndarray[start:end]
 - ndarray[start:]
 - ndarray[:end]

In [39]:
x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [40]:
z = x[1:4 , 2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [41]:
z = x[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [45]:
z = x[:,2]
print(z)

[ 3  8 13 18]


In [43]:
z = x[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


# slicing does not copy the element of array to the other variable .


In [49]:
 x = np.arange(1,21).reshape(4,5)

In [50]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [51]:
z = x[1: , 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [52]:
z[2,2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [53]:
print(x)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


In [57]:
x = np.arange(1,21).reshape(4,5)
z = np.copy(x[1:,2:])
print(x)
print()
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [58]:
z[2,2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [59]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [63]:
indices = np.array([1,3])
print(indices)

[1 3]


In [64]:
y = x[indices,:]
print(y)

[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [65]:
z = x[:,indices]
print(z)

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [67]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [66]:
z= np.diag(x)
print(z)

[ 1  7 13 19]


In [69]:
z = np.diag(x, k=1)
print(z)

[ 2  8 14 20]


In [71]:
z = np.diag(x, k=-1)
print(z)

[ 6 12 18]


In [72]:
x= np.array([[1,2,3],[5,2,8],[1,2,3]])
print(x)

[[1 2 3]
 [5 2 8]
 [1 2 3]]


In [73]:
print(np.unique(x))

[1 2 3 5 8]
